# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Navaneeth's Laboratory
tagline:          'Lessons Learnt'
description:      'A software testing, code friendly blog by Navaneeth'
url:              rnavaneeth.github.io
baseurl:          /

author:
  name:           'Navaneeth'
  url:            https://www.linkedin.com/in/rnavaneeth

paginate:         5

# Custom vars
version:          0.0.5

github:
  repo:           https://github.com/rnavaneeth
