# Site settings
title: Navaneeth's Laboratory  
email: r.navaneeth@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I write: to keep track of what I have in the past, to ponder and to explore
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://github.com/rnavaneeth" # the base hostname & protocol for your site
twitter_username: rnavaneeth
github_username:  rnavaneeth
facebook_username: r.navaneeth
linkedin_username: rnavaneeth
# Build settings
markdown: kramdown
